CREATE FUNCTION FaturamentoNota(@NUMERO AS INT) RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT

	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO]) 
	FROM [ITENS NOTAS FISCAIS]
	WHERE NUMERO = 100

	RETURN @FATURAMENTO
END;



SELECT NUMERO, dbo.FaturamentoNota(NUMERO) as FATURAMENTO  from [NOTAS FISCAIS];


CREATE FUNCTION NumeroNotas( @DATA  AS DATE ) RETURNS INT
AS 
BEGIN
	DECLARE @NUMNOTAS INT

	SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
	WHERE DATA = '20170101'
	RETURN @NUMNOTAS
END

SELECT dbo.NumeroNotas('20170101') as notas



