CREATE TABLE #TABELA01 (ID VARCHAR(10) NULL, NOME VARCHAR(200) NULL)
INSERT INTO #TABELA01 VALUES (1, 'João')
INSERT INTO #TABELA01 VALUES (2, 'Pedro')

SELECT * FROM #TABELA01;

CREATE TABLE ##TABELA02 (ID VARCHAR(10) NULL, NOME VARCHAR(200) NULL)
INSERT INTO ##TABELA02 VALUES (1, 'João')
INSERT INTO ##TABELA02 VALUES (2, 'Pedro')

SELECT * FROM ##TABELA02;