SELECT 
	SUM(A.QUANTIDADE * A.PREÇO)  AS FATURAMENTO ,
	SUM(A.QUANTIDADE * A.PREÇO)/ 10  AS COMISSAO 
FROM [ITENS NOTAS FISCAIS] A 
INNER JOIN [NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO 
WHERE B.CPF = '1471156710' AND YEAR(B.DATA) = 2016

SELECT 
	SUM(A.QUANTIDADE * A.PREÇO)  AS FATURAMENTO ,
	SUM(A.QUANTIDADE * A.PREÇO)/ 0  AS COMISSAO 
FROM [ITENS NOTAS FISCAIS] A 
INNER JOIN [NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO 
WHERE B.CPF = '1471156710' AND YEAR(B.DATA) = 2016


CREATE PROCEDURE TrataErroZero 
	@CPF VARCHAR(12), @ANO INT , @DENOMINADOR INT,
    @NUMERRO INT OUTPUT, @NUMLINHA INT OUTPUT
AS 
	BEGIN
		SELECT 
		SUM(A.QUANTIDADE * A.PREÇO)  AS FATURAMENTO ,
		SUM(A.QUANTIDADE * A.PREÇO) / @DENOMINADOR  AS COMISSAO 
		FROM [ITENS NOTAS FISCAIS] A 
		INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO 
		WHERE B.CPF = @CPF AND YEAR(B.DATA) = @ANO
		SELECT @NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
	END;


DECLARE @DENOMINADOR INT
DECLARE @CPF VARCHAR(12)
DECLARE @ANO INT
DECLARE @NUMERRO INT
DECLARE @NUMLINHA INT

SET @CPF = '1471156710'
SET @ANO = 2016
SET @DENOMINADOR = 0
EXEC TrataErroZero @CPF , @ANO, @DENOMINADOR, @NUMERRO OUTPUT, @NUMLINHA OUTPUT
IF (@NUMERRO <> 0)
 PRINT 'Houve um erro: ' + CONVERT(VARCHAR(30), @NUMERRO) + ' - ' + CONVERT(VARCHAR(30), @NUMLINHA)


 CREATE PROCEDURE InclusaoVendedor 
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50)
AS
BEGIN
INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
END

EXEC InclusaoVendedor '00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro'



CREATE PROCEDURE InclusaoVendedor01 
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50),
@NUMERROR AS INT OUTPUT, @ROW_ERROR_COUNT AS INT OUTPUT
AS
BEGIN
	INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
	VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	SELECT @NUMERROR = @@ERROR, @ROW_ERROR_COUNT = @@ROWCOUNT
END

DECLARE @NUMERRO AS INT, @COUNT_ROW_ERRO INT
EXEC InclusaoVendedor01 '00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro', @NUMERRO OUTPUT , @COUNT_ROW_ERRO OUTPUT
IF (@NUMERRO > 0)
	PRINT 'Ocorreu o erro ' +
		 CONVERT(VARCHAR(30), @NUMERRO ) + ' -  ' + 
		 CONVERT(VARCHAR(30), @COUNT_ROW_ERRO)

-- TRY CACTH 


DROP PROCEDURE  TrataErroZeroTray 
CREATE PROCEDURE TrataErroZeroTray 
	@CPF VARCHAR(12), @ANO INT , @DENOMINADOR INT,
    @MENSAGEM VARCHAR(50) OUTPUT
AS 
BEGIN
	BEGIN TRY
		SELECT 
		SUM(A.QUANTIDADE * A.PREÇO)  AS FATURAMENTO ,
		SUM(A.QUANTIDADE * A.PREÇO) / @DENOMINADOR  AS COMISSAO 
		FROM [ITENS NOTAS FISCAIS] A 
		INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO 
		WHERE B.CPF = @CPF AND YEAR(B.DATA) = @ANO
	END TRY
	BEGIN CATCH 
		SET @MENSAGEM = 'Houve um erro número ' + CONVERT( varchar(30), @@ERROR)
	END CATCH
END

DECLARE @DENOMINADOR INT,
		@CPF VARCHAR(12),
		@ANO INT,
		@MENSAGEM VARCHAR(30)

SET @DENOMINADOR = 0
SET @ANO = 2016
SET @CPF = '1471156710'
SET @MENSAGEM = ''


EXEC dbo.TrataErroZeroTray @CPF,@ANO, @DENOMINADOR, @MENSAGEM OUTPUT

IF (@MENSAGEM <> '')
	PRINT @MENSAGEM


-- Funções de erro

DROP PROCEDURE  TrataErroZeroTray2 
CREATE PROCEDURE TrataErroZeroTray2 
	@CPF VARCHAR(12), @ANO INT , @DENOMINADOR INT,
    @MENSAGEM VARCHAR(MAX) OUTPUT
AS 
BEGIN
	BEGIN TRY
		SELECT 
		SUM(A.QUANTIDADE * A.PREÇO)  AS FATURAMENTO ,
		SUM(A.QUANTIDADE * A.PREÇO) / @DENOMINADOR  AS COMISSAO 
		FROM [ITENS NOTAS FISCAIS] A 
		INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO 
		WHERE B.CPF = @CPF AND YEAR(B.DATA) = @ANO
	END TRY
	BEGIN CATCH 
		SET @MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10), ERROR_NUMBER())
		SET @MENSAGEM += '\n Mensagem: ' + ERROR_MESSAGE()
		SET @MENSAGEM += '\n Grau de severidade do erro: ' + CONVERT( VARCHAR(10), ERROR_SEVERITY())
		SET @MENSAGEM += '\n Estado do erro: ' + CONVERT(VARCHAR(10),  ERROR_STATE())
		SET @MENSAGEM += '\n Número de linhas: ' +  CONVERT( VARCHAR(10), ERROR_LINE())
		SET @MENSAGEM += '\n Procedure: ' + ERROR_PROCEDURE()
	END CATCH
END


DECLARE @DENOMINADOR INT,
		@CPF VARCHAR(12),
		@ANO INT,
		@MENSAGEM VARCHAR(MAX)

SET @DENOMINADOR = 0
SET @ANO = 2016
SET @CPF = '1471156710'
SET @MENSAGEM = ''

EXEC dbo.TrataErroZeroTray2 @CPF,@ANO, @DENOMINADOR, @MENSAGEM OUTPUT

IF (@MENSAGEM <> '')
	PRINT @MENSAGEM




