DECLARE
	 @LIMITE_MINIMO INT, 
	 @LIMITE_MAXIMO INT,
	 @LIMITE_BREAK INT 

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 10
SET @LIMITE_BREAK = 4

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MINIMO
	SET @LIMITE_MINIMO += 1
	IF @LIMITE_MINIMO = @LIMITE_BREAK
		BEGIN
			PRINT 'Saindo do limite break'
			BREAK
		END
END

-- Atividade 1



IF  OBJECT_ID('NOTAS DIA' , 'U') IS NOT NULL
	DROP TABLE [NOTAS DIA]
CREATE TABLE [NOTAS DIA](
	[NUMERO NOTA] INT,
	[DATA] DATE
)

DECLARE 
	@DATA_INICIAL DATE, 
	@DATA_FINAL DATE,
	@NUMNOTAS INT

SET @DATA_INICIAL = '20170101'
SET @DATA_FINAL = '20170110'

--SET NOCOUNT ON
WHILE @DATA_INICIAL <= @DATA_FINAL
BEGIN
	SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
	WHERE DATA = @DATA_INICIAL

	PRINT CONVERT (VARCHAR(10), @DATA_INICIAL) + ' --> '
	   +  CONVERT( VARCHAR(10), @NUMNOTAS )

	INSERT INTO [NOTAS DIA] VALUES(@NUMNOTAS, @DATA_INICIAL);
	SELECT @DATA_INICIAL = DATEADD(DAY, 1, @DATA_INICIAL)
END

SELECT * FROM [NOTAS DIA]

-- Atividade 2

IF OBJECT_ID('TABELA DE NUMEROS', 'U') IS NOT NULL
	DROP TABLE [TABELA DE NUMEROS]
CREATE TABLE [TABELA DE NUMEROS] (NUMERO INT, STATUS VARCHAR(200))

DECLARE  @CONTADOR_NOTAS INT, @LIMITE_MINIMO INT , @LIMITE_MAXIMO INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 1000

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE [NUMERO] = @LIMITE_MINIMO
	IF (@CONTADOR_NOTAS > 0)
		INSERT INTO [TABELA DE NUMEROS] (NUMERO, STATUS) VALUES(@LIMITE_MINIMO, 'É nota fiscal')
	ELSE
		INSERT INTO [TABELA DE NUMEROS] (NUMERO, STATUS) VALUES (@LIMITE_MINIMO, 'Não é uma nota fiscal') 
	SET @LIMITE_MINIMO += 1
END

SELECT COUNT(STATUS), STATUS 
FROM [TABELA DE NUMEROS]
GROUP BY STATUS


IF OBJECT_ID('TABELANOTAS','U') IS NOT NULL
DROP TABLE TABELANOTAS
CREATE TABLE TABELANOTAS (DATA DATE, NUMNOTAS INT)
DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
   SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = @DATAINICIAL
   INSERT INTO TABELANOTAS (DATA, NUMNOTAS) 
    VALUES (@DATAINICIAL, dbo.NumeroNotas(@DATAINICIAL) )
   SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END
SELECT * FROM TABELANOTAS